SELECT PUBBLICAZIONI.Titolo,COUNT(ABBONAMENTI.codAbbonato) FROM PUBBLICAZIONI
LEFT JOIN ABBONAMENTI ON PUBBLICAZIONI.codPubblicazioni=ABBONAMENTI.codPubblicazioni
WHERE PUBBLICAZIONI.GR='R'
GROUP BY PUBBLICAZIONI.Titolo
HAVING COUNT(ABBONAMENTI.CODABBONATO)=0
--VISUALIZZARE GLI ABBONATI DI OGGI

SELECT * FROM ABBONATI,ABBONAMENTI
WHERE ABBONATI.codAbbonato=ABBONAMENTI.codAbbonato
AND ABBONAMENTI.dataAbbonamento=CONVERT(DATE,GETDATE(),102)

--VISUALIZZA GLI ABBONATI TRA DUE DATE
SELECT * FROM ABBONATI,ABBONAMENTI
WHERE ABBONATI.codAbbonato=ABBONAMENTI.codAbbonato
AND ABBONAMENTI.dataAbbonamento BETWEEN '2025/01/01' AND '2025/04/01'

--visualizzare per ogni pubblicazione il numero di abbonamenti
SELECT PUBBLICAZIONI.Titolo,COUNT(ABBONAMENTI.codAbbonato) as 'NUM ABBONATI' FROM PUBBLICAZIONI
LEFT JOIN ABBONAMENTI ON PUBBLICAZIONI.codPubblicazioni=ABBONAMENTI.codPubblicazioni
GROUP BY PUBBLICAZIONI.Titolo