DECLARE @ARG int = 1;

SELECT PUBBLICAZIONI.* from TRATTANO
RIGHT JOIN PUBBLICAZIONI ON PUBBLICAZIONI.codPubblicazioni = TRATTANO.codPubblicazioni
where codArgomento = @ARG

select PUBBLICAZIONI.Titolo,count(ABBONAMENTI.codAbbonato) as 'NUM. ABBONATI' from ABBONAMENTI 
RIGHT JOIN PUBBLICAZIONI ON ABBONAMENTI.codPubblicazioni = PUBBLICAZIONI.codPubblicazioni
group by PUBBLICAZIONI.Titolo

SELECT PUBBLICAZIONI.Titolo,COUNT(ABBONAMENTI.codAbbonato) AS 'NUM. ABBONATI' FROM ABBONAMENTI
RIGHT JOIN PUBBLICAZIONI ON ABBONAMENTI.codPubblicazioni = PUBBLICAZIONI.codPubblicazioni 
AND ABBONAMENTI.tipoAbbonamento='ANNUALE' 
GROUP BY PUBBLICAZIONI.Titolo
HAVING COUNT(ABBONAMENTI.codAbbonato)>5000



select ABBONAMENTI.codPubblicazioni,COUNT(ABBONAMENTI.codAbbonato) AS 'NUM. ABBONAMENTI'
FROM ABBONAMENTI
GROUP BY ABBONAMENTI.codPubblicazioni

SELECT COUNT(ABBONAMENTI.codAbbonato) AS 'NUM ABBONATI DI 1 E 3'
FROM ABBONAMENTI
WHERE codPubblicazioni=1 OR codPubblicazioni=3

SELECT * FROM PUBBLICAZIONI

SELECT PUBBLICAZIONI.TITOLO,ABBONAMENTI.*,ABBONATI.cognome FROM ABBONAMENTI
LEFT JOIN PUBBLICAZIONI ON ABBONAMENTI.codPubblicazioni = PUBBLICAZIONI.codPubblicazioni
RIGHT JOIN ABBONATI ON ABBONAMENTI.codAbbonato = ABBONATI.codAbbonato


SELECT ABBONATI.cognome,COUNT(*) AS 'NUM. ABBONAMENTI' FROM ABBONAMENTI
LEFT JOIN PUBBLICAZIONI ON ABBONAMENTI.codPubblicazioni = PUBBLICAZIONI.codPubblicazioni
LEFT JOIN ABBONATI ON ABBONAMENTI.codAbbonato = ABBONATI.codAbbonato
GROUP BY ABBONATI.cognome

select * from ABBONAMENTI
SELECT PUBBLICAZIONI.codPubblicazioni,PUBBLICAZIONI.Titolo,ABBONAMENTI.idAbbonamento,ABBONAMENTI.codPubblicazioni,ABBONAMENTI.codAbbonato,ABBONATI.codAbbonato,ABBONATI.cognome FROM ABBONAMENTI
LEFT JOIN ABBONATI ON ABBONAMENTI.codAbbonato = ABBONATI.codAbbonato
LEFT JOIN PUBBLICAZIONI ON ABBONAMENTI.codPubblicazioni = PUBBLICAZIONI.codPubblicazioni
WHERE abbonamenti.codPubblicazioni=1 OR abbonamenti.codPubblicazioni=3


DECLARE @PUB1 VARCHAR(50) = 'pubblicazione1';
DECLARE @PUB2 VARCHAR(50) = 'pubblicazione3';
SELECT * FROM ABBONAMENTI

SELECT A.* FROM ABBONATI A
WHERE A.codAbbonato IN(SELECT AB.codAbbonato FROM ABBONAMENTI AB JOIN PUBBLICAZIONI P ON AB.codPubblicazioni=P.codPubblicazioni WHERE P.Titolo=@PUB1)
AND A.codAbbonato IN(SELECT AB.codAbbonato FROM ABBONAMENTI AB JOIN PUBBLICAZIONI P ON AB.codPubblicazioni=P.codPubblicazioni WHERE P.Titolo=@PUB2)
SELECT P1.TITOLO,AB1.codPubblicazioni ,A.* FROM ABBONATI A
RIGHT JOIN ABBONAMENTI AB1 ON A.codAbbonato=AB1.codAbbonato
INNER JOIN PUBBLICAZIONI P1 ON P1.codPubblicazioni=AB1.codPubblicazionI AND P1.Titolo=@PUB1
RIGHT JOIN ABBONAMENTI AB2 ON A.codAbbonato=AB2.codAbbonato
INNER JOIN PUBBLICAZIONI P2 ON P2.codPubblicazioni=AB2.codPubblicazionI AND P2.Titolo=@PUB2
ORDER BY AB1.codPubblicazioni
--JOIN PUBBLICAZIONI P1 ON AB1.codPubblicazioni=P1.codPubblicazioni AND P1.Titolo=@PUB1
--JOIN ABBONAMENTI AB2 ON A.codAbbonato=AB2.codAbbonato
--JOIN PUBBLICAZIONI P2 ON AB2.codPubblicazioni=P2.codPubblicazioni AND P2.Titolo=@PUB2
--SIMCRONIZZARE 
--SINCRONIZZARE
--SINCRONIZZARE
--SINCRONIZZARE
--SINCRONIZZARE
--SINCRONIZZARE
--SINCRONO<<ARE
--SOMVRPMOZZARE
--SOMCRPMO<<ARE
--SINCRONIZZARE
--SINCRONIZZARE
--ALUNNO
--CLUSTED
--DATABASE
--COMMAND
--DATA ADAPTER